// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lktgcppqssaqmwigrklx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrdGdjcHBxc3NhcW13aWdya2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjI1NTUsImV4cCI6MjA2MTk5ODU1NX0.WdC8Dnjntxq2SPyWwHffWc_9Uq63Jd0ARtaa0DvaU3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);